In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../input/winequality-red.csv")

data.head()

fixed acidity  volatile acidity   ...     alcohol  quality
0            7.4              0.70   ...         9.4        5
1            7.8              0.88   ...         9.8        5
2            7.8              0.76   ...         9.8        5
3           11.2              0.28   ...         9.8        6
4            7.4              0.70   ...         9.4        5

[5 rows x 12 columns]

In [3]:
data.count()

fixed acidity           1599
volatile acidity        1599
citric acid             1599
residual sugar          1599
chlorides               1599
free sulfur dioxide     1599
total sulfur dioxide    1599
density                 1599
pH                      1599
sulphates               1599
alcohol                 1599
quality                 1599
dtype: int64

In [4]:
data['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [5]:
list(data)

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [6]:
x = data.drop('quality',axis=1)
y = data['quality']

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.tree import DecisionTreeClassifier

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [9]:
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

accuracy_score(y_test,y_pred)

0.61875

In [10]:
confusion_matrix(y_test,y_pred)

array([[ 0,  0,  1,  0,  0,  0],
       [ 1,  1,  5,  6,  1,  0],
       [ 2,  6, 91, 31,  4,  0],
       [ 0,  2, 29, 86, 15,  1],
       [ 0,  0,  3, 12, 19,  2],
       [ 0,  0,  0,  0,  1,  1]])

In [11]:
from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier(n_estimators=3)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

accuracy_score(y_test,y_pred)

0.55

In [12]:
confusion_matrix(y_test,y_pred)

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  0,  9,  5,  0,  0],
       [ 0,  0, 97, 37,  0,  0],
       [ 0,  0, 54, 79,  0,  0],
       [ 0,  0,  6, 30,  0,  0],
       [ 0,  0,  1,  1,  0,  0]])

In [13]:
from xgboost import XGBClassifier

clf = XGBClassifier(n_estimators=200)
clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

accuracy_score(y_pred,y_test)

0.66875

In [14]:
confusion_matrix(y_test,y_pred)

array([[  0,   0,   1,   0,   0,   0],
       [  1,   0,   9,   4,   0,   0],
       [  0,   0, 102,  31,   1,   0],
       [  0,   0,  35,  94,   4,   0],
       [  0,   0,   0,  17,  18,   1],
       [  0,   0,   0,   1,   1,   0]])

In [15]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(n_estimators=150)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

accuracy_score(y_test,y_pred)

0.6625

In [16]:
confusion_matrix(y_test,y_pred)

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  0,  9,  5,  0,  0],
       [ 0,  0, 99, 35,  0,  0],
       [ 0,  0, 30, 96,  7,  0],
       [ 0,  0,  1, 18, 17,  0],
       [ 0,  0,  0,  1,  1,  0]])

In [17]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_predict

kfold = KFold(n_splits=10)

clf = DecisionTreeClassifier()
cvp = cross_val_predict(clf,x_train,y_train,cv=kfold)

accuracy_score(y_train,cvp)

0.6129788897576232

In [18]:
from sklearn.ensemble import AdaBoostClassifier

kfold = KFold(n_splits=10)
clf = AdaBoostClassifier(n_estimators=3)

cvp = cross_val_predict(clf,x_train,y_train,cv=kfold)

accuracy_score(y_train,cvp)

0.5551211884284597

In [19]:
from xgboost import XGBClassifier

kfold = KFold(n_splits=20)
clf = XGBClassifier(n_estimators=200)

cvp = cross_val_predict(clf,x_train,y_train,cv=kfold)

accuracy_score(y_train,cvp)

0.6317435496481626

In [20]:
from sklearn.ensemble import GradientBoostingClassifier

kfold = KFold(n_splits=20)
clf = GradientBoostingClassifier(n_estimators=150)

cvp = cross_val_predict(clf,x_train,y_train,cv=kfold)

accuracy_score(y_train,cvp)

0.6442533229085223